export const LOAD_MOVIES_START = "LOAD_MOVIES_START";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED";

export const FETCH_SPECIFIC_START = "FETCH_SPECIFIC_START"
export const FETCH_SPECIFIC_SUCCESS = "FETCH_SPECIFIC_SUCCESS";
export const FETCH_SPECIFIC_FAILED = "FETCH_SPECIFIC_FAILED";

export const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES";
export const REMOVE_FROM_FAVOURITES = "REMOVE_FROM_FAVOURITES";
