export const LOAD_START = "LOAD_START";

export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED";

export const FETCH_SPECIFIC_SUCCESS = "FETCH_SPECIFIC_SUCCESS";
export const FETCH_SPECIFIC_FAILED = "FETCH_SPECIFIC_FAILED";
